language: node_js
node_js: ["6.11.*"]

before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g codeclimate-test-reporter

after_success:
  - istanbul cover _mocha -- -R spec ./test/*.js
  - codeclimate-test-reporter < ./coverage/lcov.info
